name: build-staticpages

on:
  push:
    branches:
      - main
    paths:
      - 'apps/staticpages/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/staticpages

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      content: read
      packages: write
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      - name: Get short commit ID
        id: meta
        run: |
          echo "short_sha=$(echo ${{ github.sha }} | cut -c 1-7)" >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.short_sha }}
